### ISSUE TITLE
请教下大佬有没有测试过cfg下面这些配置文件的改动带来的涨点有多少？能不能推荐一些值得尝试的配置

### ISSUE THREAD

**Issue by clw5180** [GiantPandaCV/yolov3-point#1]
RT

**Comment by clw5180** [comment]
已经找到，打扰了

**Comment by JamesZhan107** [comment]
> 已经找到，打扰了

请问在哪里可以看到？

**Comment by clw5180** [comment]
> > 已经找到，打扰了
> 
> 请问在哪里可以看到？

他另外的项目，你找找

**Comment by JamesZhan107** [comment]
> > > 已经找到，打扰了
> > 
> > 
> > 请问在哪里可以看到？
> 
> 他另外的项目，你找找

他就6个repo，找了下没看见呀，能贴一下地址吗，感谢了~
