### ISSUE TITLE
请问能否给cfg文件夹每个cfg文件注释一下？

### ISSUE THREAD

**Issue by zhongqiu1245** [GiantPandaCV/yolov3-point#3]
非常感谢您的创作核分享，我是看了《从零开始学习YOLOV3》过来的
请问您所提供的cfg文件能否每个都加上一些注释，比如简单的结构介绍核功能介绍之类的，但从名字看有些可以看得出来结构，但有些看不出......

**Comment by kuangbo** [comment]
Just try  [Netron](https://github.com/lutzroeder/netron).
